// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.magalu.platform.grpc_test;

public final class TaskProto {
  private TaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TaskTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskT)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string date = 4;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string date = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code TaskT}
   */
  public  static final class TaskT extends
      com.google.protobuf.GeneratedMessageLite<
          TaskT, TaskT.Builder> implements
      // @@protoc_insertion_point(message_implements:TaskT)
      TaskTOrBuilder {
    private TaskT() {
      title_ = "";
      description_ = "";
      date_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.String title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    private void setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
    }
    /**
     * <code>optional string title = 2;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>optional string title = 2;</code>
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value.toStringUtf8();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.String description_;
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      return description_;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <code>optional string description = 3;</code>
     */
    private void setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    private void clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <code>optional string description = 3;</code>
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value.toStringUtf8();
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private java.lang.String date_;
    /**
     * <code>optional string date = 4;</code>
     */
    public java.lang.String getDate() {
      return date_;
    }
    /**
     * <code>optional string date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(date_);
    }
    /**
     * <code>optional string date = 4;</code>
     */
    private void setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
    }
    /**
     * <code>optional string date = 4;</code>
     */
    private void clearDate() {
      
      date_ = getDefaultInstance().getDate();
    }
    /**
     * <code>optional string date = 4;</code>
     */
    private void setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!title_.isEmpty()) {
        output.writeString(2, getTitle());
      }
      if (!description_.isEmpty()) {
        output.writeString(3, getDescription());
      }
      if (!date_.isEmpty()) {
        output.writeString(4, getDate());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!title_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      if (!description_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDescription());
      }
      if (!date_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDate());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.magalu.platform.grpc_test.TaskProto.TaskT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code TaskT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.magalu.platform.grpc_test.TaskProto.TaskT, Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskT)
        com.magalu.platform.grpc_test.TaskProto.TaskTOrBuilder {
      // Construct using com.magalu.platform.grpc_test.TaskProto.TaskT.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        return instance.getDescription();
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional string date = 4;</code>
       */
      public java.lang.String getDate() {
        return instance.getDate();
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        return instance.getDateBytes();
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        copyOnWrite();
        instance.setDate(value);
        return this;
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder clearDate() {
        copyOnWrite();
        instance.clearDate();
        return this;
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDateBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskT)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.magalu.platform.grpc_test.TaskProto.TaskT();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.magalu.platform.grpc_test.TaskProto.TaskT other = (com.magalu.platform.grpc_test.TaskProto.TaskT) arg1;
          id_ = visitor.visitInt(id_ != 0, id_,
              other.id_ != 0, other.id_);
          title_ = visitor.visitString(!title_.isEmpty(), title_,
              !other.title_.isEmpty(), other.title_);
          description_ = visitor.visitString(!description_.isEmpty(), description_,
              !other.description_.isEmpty(), other.description_);
          date_ = visitor.visitString(!date_.isEmpty(), date_,
              !other.date_.isEmpty(), other.date_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  id_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  title_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  description_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  date_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.magalu.platform.grpc_test.TaskProto.TaskT.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TaskT)
    private static final com.magalu.platform.grpc_test.TaskProto.TaskT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaskT();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.magalu.platform.grpc_test.TaskProto.TaskT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TaskT> PARSER;

    public static com.google.protobuf.Parser<TaskT> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface TaskListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    java.util.List<com.magalu.platform.grpc_test.TaskProto.TaskT> 
        getTasksList();
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    com.magalu.platform.grpc_test.TaskProto.TaskT getTasks(int index);
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    int getTasksCount();
  }
  /**
   * Protobuf type {@code TaskList}
   */
  public  static final class TaskList extends
      com.google.protobuf.GeneratedMessageLite<
          TaskList, TaskList.Builder> implements
      // @@protoc_insertion_point(message_implements:TaskList)
      TaskListOrBuilder {
    private TaskList() {
      tasks_ = emptyProtobufList();
    }
    public static final int TASKS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.magalu.platform.grpc_test.TaskProto.TaskT> tasks_;
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    public java.util.List<com.magalu.platform.grpc_test.TaskProto.TaskT> getTasksList() {
      return tasks_;
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    public java.util.List<? extends com.magalu.platform.grpc_test.TaskProto.TaskTOrBuilder> 
        getTasksOrBuilderList() {
      return tasks_;
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    public int getTasksCount() {
      return tasks_.size();
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    public com.magalu.platform.grpc_test.TaskProto.TaskT getTasks(int index) {
      return tasks_.get(index);
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    public com.magalu.platform.grpc_test.TaskProto.TaskTOrBuilder getTasksOrBuilder(
        int index) {
      return tasks_.get(index);
    }
    private void ensureTasksIsMutable() {
      if (!tasks_.isModifiable()) {
        tasks_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tasks_);
       }
    }

    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void setTasks(
        int index, com.magalu.platform.grpc_test.TaskProto.TaskT value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTasksIsMutable();
      tasks_.set(index, value);
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void setTasks(
        int index, com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
      ensureTasksIsMutable();
      tasks_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void addTasks(com.magalu.platform.grpc_test.TaskProto.TaskT value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTasksIsMutable();
      tasks_.add(value);
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void addTasks(
        int index, com.magalu.platform.grpc_test.TaskProto.TaskT value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTasksIsMutable();
      tasks_.add(index, value);
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void addTasks(
        com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
      ensureTasksIsMutable();
      tasks_.add(builderForValue.build());
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void addTasks(
        int index, com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
      ensureTasksIsMutable();
      tasks_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void addAllTasks(
        java.lang.Iterable<? extends com.magalu.platform.grpc_test.TaskProto.TaskT> values) {
      ensureTasksIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, tasks_);
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void clearTasks() {
      tasks_ = emptyProtobufList();
    }
    /**
     * <code>repeated .TaskT tasks = 1;</code>
     */
    private void removeTasks(int index) {
      ensureTasksIsMutable();
      tasks_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tasks_.size(); i++) {
        output.writeMessage(1, tasks_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tasks_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.TaskList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.magalu.platform.grpc_test.TaskProto.TaskList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code TaskList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.magalu.platform.grpc_test.TaskProto.TaskList, Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskList)
        com.magalu.platform.grpc_test.TaskProto.TaskListOrBuilder {
      // Construct using com.magalu.platform.grpc_test.TaskProto.TaskList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public java.util.List<com.magalu.platform.grpc_test.TaskProto.TaskT> getTasksList() {
        return java.util.Collections.unmodifiableList(
            instance.getTasksList());
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public int getTasksCount() {
        return instance.getTasksCount();
      }/**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public com.magalu.platform.grpc_test.TaskProto.TaskT getTasks(int index) {
        return instance.getTasks(index);
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder setTasks(
          int index, com.magalu.platform.grpc_test.TaskProto.TaskT value) {
        copyOnWrite();
        instance.setTasks(index, value);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder setTasks(
          int index, com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
        copyOnWrite();
        instance.setTasks(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder addTasks(com.magalu.platform.grpc_test.TaskProto.TaskT value) {
        copyOnWrite();
        instance.addTasks(value);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder addTasks(
          int index, com.magalu.platform.grpc_test.TaskProto.TaskT value) {
        copyOnWrite();
        instance.addTasks(index, value);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder addTasks(
          com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
        copyOnWrite();
        instance.addTasks(builderForValue);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder addTasks(
          int index, com.magalu.platform.grpc_test.TaskProto.TaskT.Builder builderForValue) {
        copyOnWrite();
        instance.addTasks(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder addAllTasks(
          java.lang.Iterable<? extends com.magalu.platform.grpc_test.TaskProto.TaskT> values) {
        copyOnWrite();
        instance.addAllTasks(values);
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder clearTasks() {
        copyOnWrite();
        instance.clearTasks();
        return this;
      }
      /**
       * <code>repeated .TaskT tasks = 1;</code>
       */
      public Builder removeTasks(int index) {
        copyOnWrite();
        instance.removeTasks(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.magalu.platform.grpc_test.TaskProto.TaskList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          tasks_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.magalu.platform.grpc_test.TaskProto.TaskList other = (com.magalu.platform.grpc_test.TaskProto.TaskList) arg1;
          tasks_= visitor.visitList(tasks_, other.tasks_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!tasks_.isModifiable()) {
                    tasks_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(tasks_);
                  }
                  tasks_.add(
                      input.readMessage(com.magalu.platform.grpc_test.TaskProto.TaskT.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.magalu.platform.grpc_test.TaskProto.TaskList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TaskList)
    private static final com.magalu.platform.grpc_test.TaskProto.TaskList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaskList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.magalu.platform.grpc_test.TaskProto.TaskList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TaskList> PARSER;

    public static com.google.protobuf.Parser<TaskList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageLite<
          Empty, Empty.Builder> implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
    private Empty() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.magalu.platform.grpc_test.TaskProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.magalu.platform.grpc_test.TaskProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.magalu.platform.grpc_test.TaskProto.Empty, Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.magalu.platform.grpc_test.TaskProto.EmptyOrBuilder {
      // Construct using com.magalu.platform.grpc_test.TaskProto.Empty.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.magalu.platform.grpc_test.TaskProto.Empty();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.magalu.platform.grpc_test.TaskProto.Empty other = (com.magalu.platform.grpc_test.TaskProto.Empty) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.magalu.platform.grpc_test.TaskProto.Empty.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.magalu.platform.grpc_test.TaskProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Empty();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.magalu.platform.grpc_test.TaskProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Empty> PARSER;

    public static com.google.protobuf.Parser<Empty> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
